### ISSUE TITLE
demo_training not fully executable

### ISSUE THREAD

**Issue by andrzejnovak** [pyhf/neos#11]
`_Config` seems to be missing a param
![image](https://user-images.githubusercontent.com/13226500/80492194-f72e5d80-8963-11ea-9271-a3b7124b8dbd.png)

and the plotter does not match the network output shape
![image](https://user-images.githubusercontent.com/13226500/80492367-32c92780-8964-11ea-940c-3652523ed3c8.png)

![image](https://user-images.githubusercontent.com/13226500/80492435-4bd1d880-8964-11ea-8be0-9e3688d7f7f1.png)

**Comment by phinate** [comment]
Thanks -- good catch! This is me forgetting to turn something off I was experimenting with.

I'll push something by the end of the day, but for now if you want to use it, just change `bounds` in `fit` to `m.config.suggested_bounds()`.

**Comment by andrzejnovak** [comment]
👍 cheers

You might want to consider adding papermill to test your notebooks before merging :)
